[phases.setup]
nixPkgs = ["python311", "ffmpeg", "nodePackages.nodejs", "curl"]

[phases.install]
cmds = [
  "python3.11 -m pip install --break-system-packages --upgrade 'yt-dlp[default]' python-telegram-bot",
  "curl -fsSL https://deno.land/install.sh | DENO_INSTALL=/usr/local sh"
]

[start]
cmd = "python3.11 bot.py"
