[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "ffmpeg", "nodePackages.nodejs"]

[phases.install]
cmds = [
  "python3.11 -m pip install --upgrade 'yt-dlp[default]' python-telegram-bot",
  "curl -fsSL https://deno.land/install.sh | DENO_INSTALL=/usr/local sh"
]

[start]
cmd = "python3.11 bot.py"
